name: publish

on:
  push:
    branches:
      - "master"
jobs:
  publish-byteus-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

    - uses: docker/login-action@v1
      with:
        registry: ghcr.io/${{ github.actor }}/byteus_backend:v0.1
        username: ${{ github.actor }}
        password: ${{ secrets.BYTEUS_PAT }}
    # - uses: whoan/docker-build-with-cache-action@v5
    #   with:
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.BYTEUS_PAT }}
    #     registry: ghcr.io
    #     compose_file: docker-compose.yml
    -
        name: Build and push
        uses: docker/bake-action@master
        with:
          push: true



      # This is the a separate action that sets up buildx runner
    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v1
    # # So now you can use Actions' own caching!
    # - name: Cache Docker layers
    #   uses: actions/cache@v2
    #   with:
    #     path: /tmp/.buildx-cache
    #     key: ${{ runner.os }}-buildx-${{ github.sha }}
    #     restore-keys: |
    #       ${{ runner.os }}-buildx-
    # - name: Login to GitHub Container Registry
    #   uses: docker/login-action@v1
    #   with:
    #     registry: ghcr.io
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.BYTEUS_PAT }}

    # - name: Build and push
    #         uses: docker/build-push-action@v2
    #         with:
    #           context: .
    #           push: true
    #           load: true
    #           tags: user/app:latest
    #           cache-from: type=local,src=/tmp/.buildx-cache
    #           cache-to: type=local,dest=/tmp/.buildx-cache-new
    #         # This ugly bit is necessary if you don't want your cache to grow forever
    #         # till it hits GitHub's limit of 5GB.
    #         # Temp fix
    #         # https://github.com/docker/build-push-action/issues/252
    #         # https://github.com/moby/buildkit/issues/1896
    #       - name: Move cache
    #         run: |
    #           rm -rf /tmp/.buildx-cache
    #           mv /tmp/.buildx-cache-new /tmp/.buildx-cache
    # - name: Image digest
    #     run: echo ${{ steps.docker_build.outputs.digest }}